In [4]:
import torch
x=torch.arange(12)
print(x)
print(x.shape)
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [9]:
x1=torch.reshape(x,(3,4))
#或者由-1自动计算它的维度
# x1=torch.reshape(x,(-1,4))
# x1=torch.reshape(x,(3,-1))
print(x1)
print(x1.shape)
print(x1.numel())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
12


In [14]:
x_Zeros=torch.zeros((3,4,2))#维度是逐级递减的
print(x_Zeros)
x_Ones=torch.ones((3,4,2))
print(x_Ones)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])


In [16]:
#随机创建符合高斯分布的数组
x_g=torch.randn((3,4))
x_g

tensor([[-0.1471, -0.0353, -0.4368, -1.4100],
        [ 0.9692,  0.7871,  0.4251,  0.5762],
        [ 0.7350, -0.6314,  0.5914,  3.6466]])

In [18]:
#将python的列表转化为张量
li=[[1,2,3,4],[2,2,3,4],[3,2,3,4]]
x_li=torch.tensor(li)
print(x_li)

tensor([[1, 2, 3, 4],
        [2, 2, 3, 4],
        [3, 2, 3, 4]])


In [27]:
#tensor的数值运算
x2=torch.tensor([1.0,2,3.0,4])
y2=torch.tensor([2,2,2,2])
print(x2+y2)
print(x2-y2)

print(x2*y2)
print(x2/y2)

print(x2**y2)
print(x2%y2)
#因为张量其中有一个是浮点数所以它的所有值都是浮点数

print(torch.exp(x2))

tensor([3., 4., 5., 6.])
tensor([-1.,  0.,  1.,  2.])
tensor([2., 4., 6., 8.])
tensor([0.5000, 1.0000, 1.5000, 2.0000])
tensor([ 1.,  4.,  9., 16.])
tensor([1., 0., 1., 0.])
tensor([ 2.7183,  7.3891, 20.0855, 54.5981])


In [33]:
x3 = torch.arange(12,dtype=torch.float32).reshape(3, 4)
y3=torch.tensor([[1.0,1,1,1],[2.0,2,2,2 ],[3.0,3,3,3]])
print(torch.cat((x3,y3),dim=0))
print(torch.cat((x3,y3),dim=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.]])
tensor([[ 0.,  1.,  2.,  3.,  1.,  1.,  1.,  1.],
        [ 4.,  5.,  6.,  7.,  2.,  2.,  2.,  2.],
        [ 8.,  9., 10., 11.,  3.,  3.,  3.,  3.]])


In [36]:
#逻辑运算
print(x3==y3)

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [37]:
x3.sum()

tensor(66.)

In [41]:
# 广播机制 处理形状不同的两个张量之间的操作
# 1、通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
# 2、对生成的数组执行按元素操作。

x4=torch.arange(3).reshape(3,1)
y4=torch.arange(2).reshape(1,2)
print(x4,y4)

print(x4+y4)
#x4扩展了列（复制的第一列）跟y4有相同的列
#y4扩展了行（复制的第一行）跟x4有相同的行

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [50]:
x5=torch.arange(12).reshape(3,4)
print(x5)
print(x5[2])
print(x5[2,1])
x5[2]=88
print(x5)
x5[2,1]=99
print(x5)
x5[0:2,1]=33
print(x5)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 8,  9, 10, 11])
tensor(9)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [88, 88, 88, 88]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [88, 99, 88, 88]])
tensor([[ 0, 33,  2,  3],
        [ 4, 33,  6,  7],
        [88, 99, 88, 88]])


In [51]:
#节省内存
#x=x+y会开辟一个新的内存空间，从而x不在以前x的内存空间,可以用id来看他们的内存地址是否一样
before=id(x4)
x4=x4+y4
now=id(x4)
print(now==before)

False


In [53]:
#解决方法1  使用切片表示法将操作的结果分配给先前分配的数组
z=torch.zeros_like(x4)
print("id(z)",id(z))
z[:]=x4+y4
print("id(z)",id(z))

id(z) 4729566720
id(z) 4729566720


In [55]:
# 解决方法2 使用X[:] = X + Y或X += Y来减少操作的内存开销
before1 = id(x4)
x4[:]=x4+y4
now1=id(x4)
print(now1==before1)

before2 = id(x4)
x4+=y4
now2=id(x4)
print(now2==before2)

True
True


In [59]:
# 张量转换为NumPy张量（ndarray)
x5=x4.numpy()
y5=torch.Tensor(x5)
print(type(x5),type(y5))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [62]:
#将大小为1的张量转换为python的标量
x6=torch.tensor([3.2])
print(x6,x6.item(),float(x6),int(x6))

(tensor([3.2000]), 3.200000047683716, 3.200000047683716, 3)