In [1]:
import torch
A=torch.arange(20,dtype=torch.float32).reshape([5,4])
B=A.clone()#重新分配内存，将A的一个副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [2]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [3]:
A.sum()

tensor(190.)

In [6]:
A_sum_axis1=A.sum(axis=0)#按行 即求每一列的所有行的sum
A_sum_axis2 = A.sum(axis=1)# 按列 即求每一行的所有列的sum
A_sum_axis1,A_sum_axis2,A.sum(axis=[0,1])

(tensor([40., 45., 50., 55.]), tensor([ 6., 22., 38., 54., 70.]), tensor(190.))

In [9]:
#求平均值
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [11]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [15]:
sum_A = A.sum(axis=1, keepdim=True)  # keepdim=True保持了数据原始所在的维度
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [18]:
A/sum_A #利用广播机制 相当于A的每一列都对应处以了sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [20]:
#cumsum累加求和 ，每一个元素值都是当前维度之前的元素和当前元素的值之和
A,A.cumsum(axis=0)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

In [29]:
#两个向量之间求点积，注意两个向量的元素类型必须相同
C=torch.arange(4,dtype=float)
D = torch.ones(4, dtype=float)
torch.dot(C,D)

tensor(6., dtype=torch.float64)

In [36]:
#矩阵乘法
A,B,A.shape,B.shape,torch.mm(A,B.T)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 torch.Size([5, 4]),
 tensor([[  14.,   38.,   62.,   86.,  110.],
         [  38.,  126.,  214.,  302.,  390.],
         [  62.,  214.,  366.,  518.,  670.],
         [  86.,  302.,  518.,  734.,  950.],
         [ 110.,  390.,  670.,  950., 1230.]]))

In [37]:
#L1范数 向量元素的绝对值之和
u=torch.tensor([3.0,4.0])
torch.abs(u).sum()

tensor(7.)

In [38]:
# L2范数 向量元素的平方和的平方根（在距离上也就是欧几里得距离）||x||常不带下标2
torch.norm(u)

tensor(5.)

In [39]:
#Lp范数 向量的每个元素的绝对值的p次方和的p次根
#Frobenius范数 是矩阵形式的L2范数
torch.norm(torch.ones((4,9)))

tensor(6.)

# 为什么要范数？
### 试图通过范数解决优化问题，最大化分配给观测数据的概率，最小化预测值和真实观测之间的距离。
### 用向量表示物品，以便最小化相似项目之间的距离，最大化不同项目之间的距离
